version: "3.8"

services:
  backend:
    image: gitea.nilbyte.com.br/${GITEA_REPOSITORY:-notnilton/almeida}/backend:latest
    restart: always
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}

  frontend:
    image: gitea.nilbyte.com.br/${GITEA_REPOSITORY:-notnilton/almeida}/frontend:latest
    restart: always
    ports:
      - "8080:80"

  backoffice:
    image: gitea.nilbyte.com.br/${GITEA_REPOSITORY:-notnilton/almeida}/backoffice:latest
    restart: always
    ports:
      - "5173:80"
