version: "3.8"

services:
  backend:
    image: gitea.nilbyte.com.br/${GITEA_REPOSITORY:-notnilton/almeida}/backend:latest
    restart: always
    ports:
      - "4201:3000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}

  backoffice:
    image: gitea.nilbyte.com.br/${GITEA_REPOSITORY:-notnilton/almeida}/backoffice:latest
    restart: always
    ports:
      - "4202:80"
